[package]
name = "BlindDPI"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8.0"
pnet = "0.35"
pnet_transport = "0.35"
nix = { version = "0.29", features = ["signal"] }
sysinfo = "0.33"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"

[target.'cfg(target_os = "linux")'.dependencies]
nfq = "0.2.5"

[target.'cfg(windows)'.dependencies]
windivert = { version = "0.6", features = ["vendored"] }