[package]
name = "BlindDPI"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8.0"
pnet = "0.35"

[target.'cfg(target_os = "linux")'.dependencies]
pnet_transport = "0.35"
nfq = "0.2.5"

[target.'cfg(windows)'.dependencies]
windivert = { version = "0.6", features = ["vendored"] }